### ISSUE TITLE
Add role group functionality

### ISSUE THREAD

**Issue by Christian-Toney** [DaDragonDen/toasty#9]
# Description
If users obtain a role, then the bot adds multiple other roles.

When we verify members, we simply add the Everydragon role while Toasty adds the "Event Roles" and "Personal" roles. This is a security risk because new, malicious members with roles can DM other members. 

Role groups will solve this problem; members join without roles, we give them Everydragon, and *then* the bot may add the rest of the roles. 

# Slash commands
## /group create `<base: @role>`
1. When a user runs this command, the bot will verify that the interaction is in a server. If the interaction isn't in happening in a server, the bot will follow up with the user.

2. The bot will verify that the member has the `MANAGE_ROLES` permission. If the member doesn't have this permission, the bot will follow up with the user.

3. The bot will send a follow up, asking the user to choose from a list of server roles. [Due to Discord restrictions](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure), the bot can only list up to 25 roles. If there are more than 25 server roles, the bot will create two buttons that allow the user to shift pages.

4. After the user selects the roles, they can press the green submit button, which will create and enable the role group.

## /group delete `<base: @role>`
1. When a user runs this command, the bot will verify that the interaction is in a server. If the interaction isn't in happening in a server, the bot will follow up with the user.

2. The bot will verify that the member has the `MANAGE_ROLES` permission. If the member doesn't have this permission, the bot will follow up with the user.

3. The bot will search the database for the role group. If the bot finds the group, it will delete the document from the MongoDB collection, and then follow up with the user. Otherwise, the bot will follow up with the user, saying that the bot couldn't find the role group.

## /group list 
1. The bot will get all group roles in a server.

2. Then, the bot will return the roles to the member.

**Comment by Sudobeast** [comment]
implementing this today
